import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";

export const metadata: Metadata = {
  title: "Create Notes App",
  description: "Generated by create Notes app",
  icons: {
    icon: "/favicon.svg",
  },
  openGraph: {
    title: "Create Notes App",
    description: "Generated by create Notes app",
    url: `https://notestodo-gold.vercel.app`,
    siteName: "NOTEStodo",
    images: [
      {
        url: "https://notestodo-gold.vercel.app/notestodo_logo.png",
        width: 1200,
        height: 630,
        alt: "NOTEStodo Logo",
      },
    ],
    type: "article",
  },
};

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
  display: "swap",
});

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en" className={roboto.variable}>
      <body>
        <TanStackProvider>
          <Header />
          <main>
            {children}
            {modal}
          </main>
          <Footer />
        </TanStackProvider>
      </body>
    </html>
  );
}
